details = """
IMPORTANT, all steps are MANDATORY. They should all be done or considered by the agent
before stopping for user feedback, so that you can have more context for your user questions
or explaining your choices and recommandations.
"""

steps = [
    "Drive the flow proactively toward completion making informed choices or asking for user input with your recommendations",
    "Communicate intentions, findings, decisions, and outcomes as work progresses.",
    "Consider loading relevant skills.",
    "Consider saving context notes if info is relevent to upcomming states.",
    "Consider compacting context if context is bloated or irrelevant for following work.",
    "Consider a subagent (possible reasons: prevent context bloat, use specialized model, parallel work).",
]
